# Chapter 3. Pandas 数据处理

In [1]:
import pandas as pd
import numpy as np

food_info = pd.read_csv("food_info.csv")
print(type(food_info))  # DataFrame

# Data types: 
# object - For string values 
# int - For integer values 
# float - For float values 
# datetime - For time values 
# bool - For Boolean values 
print(food_info.dtypes)

<class 'pandas.core.frame.DataFrame'>
NDB_No               int64
Shrt_Desc           object
Water_(g)          float64
Energ_Kcal           int64
Protein_(g)        float64
Lipid_Tot_(g)      float64
Ash_(g)            float64
Carbohydrt_(g)     float64
Fiber_TD_(g)       float64
Sugar_Tot_(g)      float64
Calcium_(mg)       float64
Iron_(mg)          float64
Magnesium_(mg)     float64
Phosphorus_(mg)    float64
Potassium_(mg)     float64
Sodium_(mg)        float64
Zinc_(mg)          float64
Copper_(mg)        float64
Manganese_(mg)     float64
Selenium_(mcg)     float64
Vit_C_(mg)         float64
Thiamin_(mg)       float64
Riboflavin_(mg)    float64
Niacin_(mg)        float64
Vit_B6_(mg)        float64
Vit_B12_(mcg)      float64
Vit_A_IU           float64
Vit_A_RAE          float64
Vit_E_(mg)         float64
Vit_D_mcg          float64
Vit_D_IU           float64
Vit_K_(mcg)        float64
FA_Sat_(g)         float64
FA_Mono_(g)        float64
FA_Poly_(g)        float64
Cholestrl_(mg)     float64
dtype: object

In [2]:
# DataFrame.head([num])  default_num = 5
# DataFrame.tail([num])  default_num = 5

head = food_info.head(5)
print(head)

print('-----------------------')
print(food_info.columns)  #columns name
print(type(food_info.columns))
print('-----------------------')
print(food_info.shape)

   NDB_No                 Shrt_Desc  Water_(g)  Energ_Kcal  Protein_(g)  \
0    1001          BUTTER WITH SALT      15.87         717         0.85
1    1002  BUTTER WHIPPED WITH SALT      15.87         717         0.85
2    1003      BUTTER OIL ANHYDROUS       0.24         876         0.28
3    1004               CHEESE BLUE      42.41         353        21.40
4    1005              CHEESE BRICK      41.11         371        23.24

   Lipid_Tot_(g)  Ash_(g)  Carbohydrt_(g)  Fiber_TD_(g)  Sugar_Tot_(g)  \
0          81.11     2.11            0.06           0.0           0.06
1          81.11     2.11            0.06           0.0           0.06
2          99.48     0.00            0.00           0.0           0.00
3          28.74     5.11            2.34           0.0           0.50
4          29.68     3.18            2.79           0.0           0.51

        ...        Vit_A_IU  Vit_A_RAE  Vit_E_(mg)  Vit_D_mcg  Vit_D_IU  \
0       ...          2499.0      684.0        2.32        1.5      60.0
1       ...          2499.0      684.0        2.32        1.5      60.0
2       ...          3069.0      840.0        2.80        1.8      73.0
3       ...           721.0      198.0        0.25        0.5      21.0
4       ...          1080.0      292.0        0.26        0.5      22.0

   Vit_K_(mcg)  FA_Sat_(g)  FA_Mono_(g)  FA_Poly_(g)  Cholestrl_(mg)
0          7.0      51.368       21.021        3.043           215.0
1          7.0      50.489       23.426        3.012           219.0
2          8.6      61.924       28.732        3.694           256.0
3          2.4      18.669        7.778        0.800            75.0
4          2.5      18.764        8.598        0.784            94.0

[5 rows x 36 columns]
-----------------------
Index(['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)',
       'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)',
       'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)',
       'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)',
       'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)',
       'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)',
       'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg',
       'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)',
       'Cholestrl_(mg)'],
      dtype='object')
<class 'pandas.core.indexes.base.Index'>
-----------------------
(8618, 36)

In [3]:
# get row values
print(food_info.loc[0])
# print('-----------------------')
# print(food_info.loc[2])
# print('-----------------------')
# print(food_info.loc[5])

NDB_No                         1001
Shrt_Desc          BUTTER WITH SALT
Water_(g)                     15.87
Energ_Kcal                      717
Protein_(g)                    0.85
Lipid_Tot_(g)                 81.11
Ash_(g)                        2.11
Carbohydrt_(g)                 0.06
Fiber_TD_(g)                      0
Sugar_Tot_(g)                  0.06
Calcium_(mg)                     24
Iron_(mg)                      0.02
Magnesium_(mg)                    2
Phosphorus_(mg)                  24
Potassium_(mg)                   24
Sodium_(mg)                     643
Zinc_(mg)                      0.09
Copper_(mg)                       0
Manganese_(mg)                    0
Selenium_(mcg)                    1
Vit_C_(mg)                        0
Thiamin_(mg)                  0.005
Riboflavin_(mg)               0.034
Niacin_(mg)                   0.042
Vit_B6_(mg)                   0.003
Vit_B12_(mcg)                  0.17
Vit_A_IU                       2499
Vit_A_RAE                       684
Vit_E_(mg)                     2.32
Vit_D_mcg                       1.5
Vit_D_IU                         60
Vit_K_(mcg)                       7
FA_Sat_(g)                   51.368
FA_Mono_(g)                  21.021
FA_Poly_(g)                   3.043
Cholestrl_(mg)                  215
Name: 0, dtype: object

In [4]:
# get serveral row values
row = [1, 2, 5]
print(food_info.loc[row])

   NDB_No                 Shrt_Desc  Water_(g)  Energ_Kcal  Protein_(g)  \
1    1002  BUTTER WHIPPED WITH SALT      15.87         717         0.85
2    1003      BUTTER OIL ANHYDROUS       0.24         876         0.28
5    1006               CHEESE BRIE      48.42         334        20.75

   Lipid_Tot_(g)  Ash_(g)  Carbohydrt_(g)  Fiber_TD_(g)  Sugar_Tot_(g)  \
1          81.11     2.11            0.06           0.0           0.06
2          99.48     0.00            0.00           0.0           0.00
5          27.68     2.70            0.45           0.0           0.45

        ...        Vit_A_IU  Vit_A_RAE  Vit_E_(mg)  Vit_D_mcg  Vit_D_IU  \
1       ...          2499.0      684.0        2.32        1.5      60.0
2       ...          3069.0      840.0        2.80        1.8      73.0
5       ...           592.0      174.0        0.24        0.5      20.0

   Vit_K_(mcg)  FA_Sat_(g)  FA_Mono_(g)  FA_Poly_(g)  Cholestrl_(mg)
1          7.0      50.489       23.426        3.012           219.0
2          8.6      61.924       28.732        3.694           256.0
5          2.3      17.410        8.013        0.826           100.0

[3 rows x 36 columns]

In [5]:
# get column values
col_name = 'Vit_A_IU'
Vit_A_IU = food_info[col_name]
Vit_A_IU[0:10]

0    2499.0
1    2499.0
2    3069.0
3     721.0
4    1080.0
5     592.0
6     820.0
7    1054.0
8     994.0
9     985.0
Name: Vit_A_IU, dtype: float64

In [6]:
# get several column values

columns = ['Iron_(mg)', 'Magnesium_(mg)']
values = food_info[columns]
print(values[0:10])

   Iron_(mg)  Magnesium_(mg)
0       0.02             2.0
1       0.16             2.0
2       0.00             0.0
3       0.31            23.0
4       0.43            24.0
5       0.50            20.0
6       0.33            20.0
7       0.64            22.0
8       0.16            27.0
9       0.21            21.0

In [7]:
# cut part of the DataFrame
food_info.loc[2:5]

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,721.0,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,1080.0,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0
5,1006,CHEESE BRIE,48.42,334,20.75,27.68,2.70,0.45,0.0,0.45,...,592.0,174.0,0.24,0.5,20.0,2.3,17.410,8.013,0.826,100.0

In [8]:
# Filt some of the columns
# in this case- end up with 'g'
col_names = food_info.columns.tolist()  #get columns in the list
print(col_names)
print('\n\n')

gram_columns = []  #get conditional index

for col in col_names:
    if col.endswith('(g)'):
        gram_columns.append(col)

gram_data = food_info[gram_columns]
print(gram_data[0:10])

['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)', 'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)', 'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)', 'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)', 'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)', 'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)', 'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg', 'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)', 'Cholestrl_(mg)']



   Water_(g)  Protein_(g)  Lipid_Tot_(g)  Ash_(g)  Carbohydrt_(g)  \
0      15.87         0.85          81.11     2.11            0.06
1      15.87         0.85          81.11     2.11            0.06
2       0.24         0.28          99.48     0.00            0.00
3      42.41        21.40          28.74     5.11            2.34
4      41.11        23.24          29.68     3.18            2.79
5      48.42        20.75          27.68     2.70            0.45
6      51.80        19.80          24.26     3.68            0.46
7      39.28        25.18          29.20     3.28            3.06
8      37.10        24.04          33.82     3.71            1.33
9      37.65        23.37          30.60     3.60            4.78

   Fiber_TD_(g)  Sugar_Tot_(g)  FA_Sat_(g)  FA_Mono_(g)  FA_Poly_(g)
0           0.0           0.06      51.368       21.021        3.043
1           0.0           0.06      50.489       23.426        3.012
2           0.0           0.00      61.924       28.732        3.694
3           0.0           0.50      18.669        7.778        0.800
4           0.0           0.51      18.764        8.598        0.784
5           0.0           0.45      17.410        8.013        0.826
6           0.0           0.46      15.259        7.023        0.724
7           0.0            NaN      18.584        8.275        0.830
8           0.0           0.28      19.368        8.428        1.433
9           0.0            NaN      19.475        8.671        0.870

In [9]:
# basic operations
new = pd.DataFrame()
new['Sodium_(mg)'] = food_info['Sodium_(mg)']
new['add_100'] = food_info['Sodium_(mg)'] + 100
new['sub_100'] = food_info['Sodium_(mg)'] - 100
new['multiple_2'] = food_info['Sodium_(mg)'] * 2
new['div_1000'] = food_info['Sodium_(mg)'] / 1000
print(new[0:10])

   Sodium_(mg)  add_100  sub_100  multiple_2  div_1000
0        643.0    743.0    543.0      1286.0     0.643
1        659.0    759.0    559.0      1318.0     0.659
2          2.0    102.0    -98.0         4.0     0.002
3       1146.0   1246.0   1046.0      2292.0     1.146
4        560.0    660.0    460.0      1120.0     0.560
5        629.0    729.0    529.0      1258.0     0.629
6        842.0    942.0    742.0      1684.0     0.842
7        690.0    790.0    590.0      1380.0     0.690
8        644.0    744.0    544.0      1288.0     0.644
9        700.0    800.0    600.0      1400.0     0.700

In [10]:
# operations between DataFrames
new = pd.DataFrame()
new['water_energy'] = food_info['Water_(g)']
new['Energ_Kcal'] = food_info['Energ_Kcal']
new['total'] = new['water_energy'] * new['Energ_Kcal']
print(new[0:10])

   water_energy  Energ_Kcal     total
0         15.87         717  11378.79
1         15.87         717  11378.79
2          0.24         876    210.24
3         42.41         353  14970.73
4         41.11         371  15251.81
5         48.42         334  16172.28
6         51.80         300  15540.00
7         39.28         376  14769.28
8         37.10         406  15062.60
9         37.65         387  14570.55

In [11]:
# max(), min(), mean()
# normalization
max_calories = food_info["Energ_Kcal"].max()
# min_calories = food_info["Energ_Kcal"].min()
# Divide the values in "Energ_Kcal" by the largest value.
normalized_calories = food_info["Energ_Kcal"] / max_calories
normalized_protein = food_info["Protein_(g)"] / food_info["Protein_(g)"].max()
normalized_fat = food_info["Lipid_Tot_(g)"] / food_info["Lipid_Tot_(g)"].max()
food_info["Normalized_Protein"] = normalized_protein
food_info["Normalized_Fat"] = normalized_fat

In [12]:
# sort()
#By default, pandas will sort the data by the column we specify in ascending order and return a new DataFrame
# Sorts the DataFrame in-place, rather than returning a new DataFrame.
# print( food_info["Sodium_(mg)"])
food_info.sort_values("Sodium_(mg)", inplace=True)
print(food_info["Sodium_(mg)"][0:10])  # ascending， default = ture
print('------------------------')
a = food_info.sort_values("Sodium_(mg)", ascending=False)  #descending， default = ture
print(a["Sodium_(mg)"][0:10])

760     0.0
758     0.0
405     0.0
761     0.0
2269    0.0
763     0.0
764     0.0
770     0.0
774     0.0
396     0.0
Name: Sodium_(mg), dtype: float64
------------------------
276     38758.0
5814    27360.0
6192    26050.0
1242    26000.0
1245    24000.0
1243    24000.0
1244    23875.0
292     17000.0
1254    11588.0
5811    10600.0
Name: Sodium_(mg), dtype: float64